### ISSUE TITLE
change the date

### ISSUE THREAD

**Issue by joto199** [Mod8124/countDown-timer-with-typeScript#1]
Hey Denis, first of all thanks for the super code! i would like to use ur code, may i?  i wanna ask u how to change the date and put mine inside of the code,  ive made a change on the js.js but i can not understand how it wors, i want a countdown for the 29th of July 2023

**Comment by Mod8124** [comment]
Hi!
Yeah sure you can use it, I modify that, and now you can add a custom Datejust modify the `END DAY` variable
```javascript
 const END_DAY = new Date(2023,6, 29)
   // Only change to the date that you want (year, month, day)
   // Month starts from zero to eleven

   // Example Christmas
   const END_DAY = new Date(2022, 11, 24)
```

**Comment by joto199** [comment]
Thank you for ur quick answer! Your new js code it isnt working, when i put it on VS code its shows 10 faults. 
i have oppend it also from your index.hmtl file and it doesnt working :/

**Comment by Mod8124** [comment]
Mmm It's by default on the 29 of July 2023, to me works perfectly, I only changed one thing xD
```javascript
//from  
getTime(86400*14)
// the first parameter is the day's seconds and the second parameter countdown to 14 days

// to 
const SECONDS_DAY = 86400;
const START_DAY:Date = new Date();
const END_DAY:Date = new Date(2023, 6, 29)
const DAYS_UNTIL_END_DAY = Math.ceil(((END_DAY.getTime() - START_DAY.getTime()) / (1000 * 60 * 60 * 24)));
// calculate the remaining days to 29 of July 2023

getTime(SECONDS * DAYS_UNTIL_END_DAY)
// I only change the 14 to your custom date
``` 
So for the custom date, you only need to change `getTime(86400*14)` the parameter 14 and change it  to 
your custom date(remainder day to your custom date)
 By the way, if you change manually change the parameter 14(days remainder to custom date) every time call the function `getTime`

That's all, I hope helps you

**Comment by joto199** [comment]
Thanks a lot, my problem was that i put 2023, **07**, 29  but i had to put only **7**.
Now it works perfect.

PS

one last thing xD

 When im trying to make the programm works for the day after tommorow or better for the same month its shows +30 days, 
and im scared when the 2023 july comes that the countdown are going to show +30days but there will be only 25 or 10 or 1 day.

**Comment by Mod8124** [comment]
Yeah, you can't put 07 **only** 0 to 11 and by the way,  I debugged the code a little bit a works for me 
```javascript
  const START_DAY:Date = new Date(2023, 6, 28);
 // day before 
  const END_DAY:Date = new Date(2023, 6, 29)
 // here it's just 24 hours left to the 29 July 2023, so it works, 
```
 I think that your problem it's that you put 7 instead of 6 in the months, it goes  like this
- January = 0
- February = 1
- March = 2
so July it's 6 

```javascript
if(secondsLeft<=0) {
        clearInterval(countDown);
        getTime(SECONDS_DAY*DAYS_UNTIL_END_DAY);
        return // by the way I forgot this **return** for display zero on the HTML
    }
```

**Comment by joto199** [comment]
const START_DAY**:Date** = new Date(2023, 6, 28);
 // day before 
  const END_DAY**:Date** = new Date(2023, 6, 29)
 // here it's just 24 hours left to the 29 July 2023, so it works, 

when im changing the code to this new one, its shows up a fault code with this one msg "Type annotations can only be used in TypeScript files.ts(8010)" 


![fault](https://user-images.githubusercontent.com/95505848/197416553-74bbd488-b73c-413d-9c13-7dcc76556c7f.png)


This is the Code im using now and its shows the previous fault. 

"use strict";
const displayDay = document.querySelector('.displayDays  p');
const displayHour = document.querySelector('.displayHours p');
const displayMinutes = document.querySelector('.displayMinutes p');
const displaySeconds = document.querySelector('.displaySeconds p');
let countDown;
const SECONDS_DAY = 86400;
const START_DAY:Date = new Date(2023, 6, 28);
// year month day (month start from zero to eleven) 
const END_DAY:Date = new Date(2023, 6, 29);
// calculate days between START_DAY and END_DAY;
const DAYS_UNTIL_END_DAY = Math.ceil(((END_DAY - START_DAY) / (1000 * 60 * 60 * 24)));
const getTime = (secs) => {
    const now = Date.now();
    const then = now + (secs * 1000);
    displayTime(secs);
    countDown = setInterval(() => {
        const secondsLeft = Math.floor((then - Date.now()) / 1000);
        if(secondsLeft<=0) {
            clearInterval(countDown);
            getTime(SECONDS_DAY*DAYS_UNTIL_END_DAY);
            return // by the way I forgot this **return** for display zero on the HTML
        }
        displayTime(secondsLeft);
    }, 1000);
};
const displayTime = (secs) => {
    const remainderseconds = secs % 60;
    const minutes = Math.floor(secs / 60);
    const hour = Math.floor(minutes / 60);
    const days = Math.floor(hour / 24);
    displaySeconds.innerHTML = `${remainderseconds < 10 ? '0' : ""}${remainderseconds}`;
    displayMinutes.innerHTML = `${minutes > 60 ? minutes.toString().slice(-2) : minutes}`;
    displayHour.innerHTML = `${hour > 24 ? hour.toString().slice(-2) : hour}`;
    displayDay.innerHTML = `${days < 10 ? '0' : ''}${days}`;
};
getTime(SECONDS_DAY * DAYS_UNTIL_END_DAY);


Thanks in advance.

**Comment by Mod8124** [comment]
Hi!

```javascript
//just for simulation a day before July 29, 2023(you can use this for simulation dates the day before, the month after, or whatever day, month, or year you want it)
const START_DAY:Date = new Date(2023, 6, 28);
const END_DAY:Date = new Date(2023, 6, 29);
//simulate the day before July 29, 2023 (this line was just for testing)

const START_DAY:Date = new Date();
const END_DAY:Date = new Date(2023, 6, 29);
//Current date
```
The code is alright,  you don't have to modify anything just the `return` but you added it already so it's ok
by the way, your code doesn't work it's because  you're using **type checking** but it's just for typescript not for javascript

```javascript
 //TypeScript
const START_DAY:Date = new Date(2023, 6, 28);
const END_DAY:Date = new Date(2023, 6, 29);

//javaScript
const START_DAY = new Date(2023, 6, 28);
const END_DAY= new Date(2023, 6, 29);
```
